Hive update
Hive-Five-project/hive-five pull request #39
Opened 2024-05-20 20:13 UTC by KangSolC

2024-05-29 21:42 UTC, Spaicat commented on front/src/components/BeeHive/BeehiveForm.tsx
> +  const beeTypes = ['Black', 'Italian', 'Caucasian', 'Carnolien', 'Buckfast'];
Should pull this from the backend, not hardcode it.
I believe the function is called `listBeeType` in the backend, you should look into this.

2024-05-29 21:42 UTC, Spaicat commented on .vscode/settings.json
> +}
Remove this useless file

2024-05-29 21:42 UTC, Spaicat commented on front/src/components/BeeHive/BeehiveForm.tsx
> +    }
Is this better? (For not repeating too much stuff)
```suggestion
    <TopNavigationMenu
      previousPath={previousUrl ??
        (uid
          ? route(!isUpdate ? ApiaryHome : BeehiveHome, { uid })
          : route(ApiaryList))}
    />
```

2024-06-13 20:03 UTC, Spaicat approved these changes

2024-06-13 21:25 UTC, rphang requested changes, later dismissed

2024-06-13 21:25 UTC, rphang commented on front/package-lock.json
This file shouldn't be removed. It may be updated if new packages are added or updated.

2024-06-13 21:32 UTC, KangSolC commented on front/package-lock.json
windaube :') my bad. I'll fix it tomorrow

2024-06-13 21:43 UTC, rphang commented on front/package-lock.json
Nvm! It seems that the newly downloaded packages have some regression on their dependencies, my bad! LGTM.

2024-06-13 21:51 UTC, merged